from . import db


class Item(db.Model):
    __tablename__='items'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'default.jpg')
    starting_bid = db.Column(db.Integer, nullable = False)
    current_bid = db.Column(db.Integer)
    category = db.Column(db.String(20), nullable = False)
    is_closed = db.Column(db.Boolean)
    num_bid = db.Column(db.Integer)

class ROLFFile(db.Model):
    __tablename__='UpdatedplayerGame'
    GAME_ID = db.Column(db.String(64), primary_key=True)
    ASSISTS = db.Column(db.String(64))
    BARON_KILLS = db.Column(db.String(64))
    BARRACKS_KILLED = db.Column(db.String(64))
    BARRACKS_TAKEDOWNS = db.Column(db.String(64))
    BOUNTY_LEVEL = db.Column(db.String(64))
    CHAMPIONS_KILLED = db.Column(db.String(64))
    CHAMPION_TRANSFORM = db.Column(db.String(64))
    CONSUMABLES_PURCHASED = db.Column(db.String(64))
    DOUBLE_KILLS = db.Column(db.String(64))
    DRAGON_KILLS = db.Column(db.String(64))
    EXP = db.Column(db.String(64))
    FRIENDLY_DAMPEN_LOST = db.Column(db.String(64))
    FRIENDLY_HQ_LOST = db.Column(db.String(64))
    FRIENDLY_TURRET_LOST = db.Column(db.String(64))
    GAME_ENDED_IN_EARLY_SURRENDER = db.Column(db.String(64))
    GAME_ENDED_IN_SURRENDER = db.Column(db.String(64))
    GOLD_EARNED = db.Column(db.String(64))
    GOLD_SPENT = db.Column(db.String(64))
    HQ_KILLED = db.Column(db.String(64))
    HQ_TAKEDOWNS = db.Column(db.String(64))
    ID = db.Column(db.String(64))
    INDIVIDUAL_POSITION = db.Column(db.String(64))
    ITEM0 = db.Column(db.String(64))
    ITEM1 = db.Column(db.String(64))
    ITEM2 = db.Column(db.String(64))
    ITEM3 = db.Column(db.String(64))
    ITEM4 = db.Column(db.String(64))
    ITEM5 = db.Column(db.String(64))
    ITEM6 = db.Column(db.String(64))
    ITEMS_PURCHASED = db.Column(db.String(500))
    KEYSTONE_ID = db.Column(db.String(64))
    KILLING_SPREES = db.Column(db.String(64))
    LARGEST_CRITICAL_STRIKE = db.Column(db.String(64))
    LARGEST_KILLING_SPREE = db.Column(db.String(64))
    LARGEST_MULTI_KILL = db.Column(db.String(64))
    LEVEL = db.Column(db.String(64))
    LONGEST_TIME_SPENT_LIVING = db.Column(db.String(64))
    MAGIC_DAMAGE_DEALT_PLAYER = db.Column(db.String(64))
    MAGIC_DAMAGE_DEALT_TO_CHAMPIONS = db.Column(db.String(64))
    MAGIC_DAMAGE_TAKEN = db.Column(db.String(64))
    MINIONS_KILLED = db.Column(db.String(64))
    NAME = db.Column(db.String(64))
    NEUTRAL_MINIONS_KILLED = db.Column(db.String(64))
    NEUTRAL_MINIONS_KILLED_ENEMY_JUNGLE = db.Column(db.String(64))
    NEUTRAL_MINIONS_KILLED_YOUR_JUNGLE = db.Column(db.String(64))
    NUM_DEATHS = db.Column(db.String(64))
    OBJECTIVES_STOLEN = db.Column(db.String(64))
    OBJECTIVES_STOLEN_ASSISTS = db.Column(db.String(64))
    PENTA_KILLS = db.Column(db.String(64))
    PERK_PRIMARY_STYLE = db.Column(db.String(64))
    PERK_SUB_STYLE = db.Column(db.String(64))
    PHYSICAL_DAMAGE_DEALT_PLAYER = db.Column(db.String(64))
    PHYSICAL_DAMAGE_DEALT_TO_CHAMPIONS = db.Column(db.String(64))
    PHYSICAL_DAMAGE_TAKEN = db.Column(db.String(64))
    PING = db.Column(db.String(64))
    PLAYER_POSITION = db.Column(db.String(64))
    QUADRA_KILLS = db.Column(db.String(64))
    SIGHT_WARDS_BOUGHT_IN_GAME = db.Column(db.String(64))
    SKIN = db.Column(db.String(64))
    SPELL1_CAST = db.Column(db.String(64))
    SPELL2_CAST = db.Column(db.String(64))
    SPELL3_CAST = db.Column(db.String(64))
    SPELL4_CAST = db.Column(db.String(64))
    STAT_PERK_0 = db.Column(db.String(64))
    STAT_PERK_1 = db.Column(db.String(64))
    STAT_PERK_2 = db.Column(db.String(64))
    SUMMON_SPELL1_CAST = db.Column(db.String(64))
    SUMMON_SPELL2_CAST = db.Column(db.String(64))
    TEAM = db.Column(db.String(64))
    TEAM_EARLY_SURRENDERED = db.Column(db.String(64))
    TEAM_OBJECTIVE = db.Column(db.String(64))
    TEAM_POSITION = db.Column(db.String(64))
    TIME_CCING_OTHERS = db.Column(db.String(64))
    TIME_PLAYED = db.Column(db.String(64))
    TOTAL_DAMAGE_DEALT = db.Column(db.String(64))
    TOTAL_DAMAGE_DEALT_TO_BUILDINGS = db.Column(db.String(64))
    TOTAL_DAMAGE_DEALT_TO_CHAMPIONS = db.Column(db.String(64))
    TOTAL_DAMAGE_DEALT_TO_OBJECTIVES = db.Column(db.String(64))
    TOTAL_DAMAGE_DEALT_TO_TURRETS = db.Column(db.String(64))
    TOTAL_DAMAGE_SELF_MITIGATED = db.Column(db.String(64))
    TOTAL_DAMAGE_SHIELDED_ON_TEAMMATES = db.Column(db.String(64))
    TOTAL_DAMAGE_TAKEN = db.Column(db.String(64))
    TOTAL_HEAL = db.Column(db.String(64))
    TOTAL_HEAL_ON_TEAMMATES = db.Column(db.String(64))
    TOTAL_TIME_CROWD_CONTROL_DEALT = db.Column(db.String(64))
    TOTAL_TIME_SPENT_DEAD = db.Column(db.String(64))
    TOTAL_UNITS_HEALED = db.Column(db.String(64))
    TRIPLE_KILLS = db.Column(db.String(64))
    TRUE_DAMAGE_DEALT_PLAYER = db.Column(db.String(64))
    TRUE_DAMAGE_DEALT_TO_CHAMPIONS = db.Column(db.String(64))
    TRUE_DAMAGE_TAKEN = db.Column(db.String(64))
    TURRETS_KILLED = db.Column(db.String(64))
    TURRET_TAKEDOWNS = db.Column(db.String(64))
    UNREAL_KILLS = db.Column(db.String(64))
    VICTORY_POINT_TOTAL = db.Column(db.String(64))
    VISION_SCORE = db.Column(db.String(64))
    VISION_WARDS_BOUGHT_IN_GAME = db.Column(db.String(64))
    WARD_KILLED = db.Column(db.String(64))
    WARD_PLACED = db.Column(db.String(64))
    WARD_PLACED_DETECTOR = db.Column(db.String(64))
    WAS_EARLY_SURRENDER_ACCOMPLICE = db.Column(db.String(64))
    WIN = db.Column(db.String(64))


class Music(db.Model):
    __tablename__='Music'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    author = db.Column(db.String(500), nullable=False)
    audio = db.Column(db.String(60), nullable=False, default = 'default.mp3')

class Teams(db.Model):
    __tablename__='Teams'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    abbreviation = db.Column(db.String(64))
    description = db.Column(db.String(64))
    logoBlue = db.Column(db.String(64))
    logoRed = db.Column(db.String(64))
    colour= db.Column(db.String(64))
    wins = db.Column(db.String(64))
    losses = db.Column(db.String(64))

class Casters(db.Model):
    __tablename__="Casters"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    subname = db.Column(db.String(64))

class Players(db.Model):
    __tablename__="Players"
    id = db.Column(db.Integer, primary_key=True)
    puid = db.Column(db.String(256))
    name = db.Column(db.String(64))
    team = db.Column(db.String(64))
    killsavg = db.Column(db.String(64))
    deathsavg=db.Column(db.String(64))
    assistsavg=db.Column(db.String(64))
    goldavg=db.Column(db.String(64))
    winpercentage=db.Column(db.String(64))
    dmgavg=db.Column(db.String(64))
    creepscoreavg=db.Column(db.String(64))

class Match(db.Model):
    __tablename__="Matches"
    id = db.Column(db.Integer, primary_key=True)
    team1 = db.Column(db.Integer)
    team2 = db.Column(db.Integer)
    time = db.Column(db.String(64))
    format = db.Column(db.String(64))
    team1name = db.Column(db.String(64))
    team2name = db.Column(db.String(64))
    winner = db.Column(db.String(64))
    loser = db.Column(db.String(64))
    decided = db.Column(db.String(64))

class Bid(db.Model):
    __tablename__='bids'
    item_id= db.Column(db.Integer)
    user_id= db.Column(db.Integer)
    bid = db.Column(db.Integer)
    bid_id = db.Column(db.Integer, primary_key=True)

class User(db.Model):
    __tablename__='users'
    user_id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(60), nullable=False)
    email = db.Column(db.String(60), nullable=False)
    password = db.Column(db.String(500), nullable=False)
    is_buyer = db.Column(db.Boolean)
    def get_id(self):
           return (self.user_id)

class MatchStas(db.Model):
    __tablename__="StatsRiotAPI"
    id2 = db.Column(db.Integer, primary_key=True)
    Gameid = db.Column(db.String(256))
    allInPings = db.Column(db.String(256))
    assistMePings = db.Column(db.String(256))
    assists = db.Column(db.String(256))
    baronKills = db.Column(db.String(256))
    basicPings = db.Column(db.String(256))
    bountyLevel = db.Column(db.String(256))
    champExperience = db.Column(db.String(256))
    champLevel = db.Column(db.String(256))
    championId = db.Column(db.String(256))
    championName = db.Column(db.String(256))
    championTransform = db.Column(db.String(256))
    commandPings = db.Column(db.String(256))
    consumablesPurchased = db.Column(db.String(256))
    damageDealtToBuildings = db.Column(db.String(256))
    damageDealtToObjectives = db.Column(db.String(256))
    damageDealtToTurrets = db.Column(db.String(256))
    damageSelfMitigated = db.Column(db.String(256))
    dangerPings = db.Column(db.String(256))
    deaths = db.Column(db.String(256))
    detectorWardsPlaced = db.Column(db.String(256))
    doubleKills = db.Column(db.String(256))
    dragonKills = db.Column(db.String(256))
    eligibleForProgression = db.Column(db.String(256))
    enemyMissingPings = db.Column(db.String(256))
    enemyVisionPings = db.Column(db.String(256))
    firstBloodAssist = db.Column(db.String(256))
    firstBloodKill = db.Column(db.String(256))
    firstTowerAssist = db.Column(db.String(256))
    firstTowerKill = db.Column(db.String(256))
    gameEndedInEarlySurrender = db.Column(db.String(256))
    gameEndedInSurrender = db.Column(db.String(256))
    getBackPings = db.Column(db.String(256))
    goldEarned = db.Column(db.String(256))
    goldSpent = db.Column(db.String(256))
    holdPings = db.Column(db.String(256))
    individualPosition = db.Column(db.String(256))
    inhibitorKills = db.Column(db.String(256))
    inhibitorTakedowns = db.Column(db.String(256))
    inhibitorsLost = db.Column(db.String(256))
    item0 = db.Column(db.String(256))
    item1 = db.Column(db.String(256))
    item2 = db.Column(db.String(256))
    item3 = db.Column(db.String(256))
    item4 = db.Column(db.String(256))
    item5 = db.Column(db.String(256))
    item6 = db.Column(db.String(256))
    itemsPurchased = db.Column(db.String(256))
    killingSprees = db.Column(db.String(256))
    kills = db.Column(db.String(256))
    lane = db.Column(db.String(256))
    largestCriticalStrike = db.Column(db.String(256))
    largestKillingSpree = db.Column(db.String(256))
    largestMultiKill = db.Column(db.String(256))
    longestTimeSpentLiving = db.Column(db.String(256))
    magicDamageDealt = db.Column(db.String(256))
    magicDamageDealtToChampions = db.Column(db.String(256))
    magicDamageTaken = db.Column(db.String(256))
    needVisionPings = db.Column(db.String(256))
    neutralMinionsKilled = db.Column(db.String(256))
    nexusKills = db.Column(db.String(256))
    nexusLost = db.Column(db.String(256))
    nexusTakedowns = db.Column(db.String(256))
    objectivesStolen = db.Column(db.String(256))
    objectivesStolenAssists = db.Column(db.String(256))
    onMyWayPings = db.Column(db.String(256))
    participantId = db.Column(db.String(256))
    pentaKills = db.Column(db.String(256))
    physicalDamageDealt = db.Column(db.String(256))
    physicalDamageDealtToChampions = db.Column(db.String(256))
    physicalDamageTaken = db.Column(db.String(256))
    placement = db.Column(db.String(256))
    playerAugment1 = db.Column(db.String(256))
    playerAugment2 = db.Column(db.String(256))
    playerAugment3 = db.Column(db.String(256))
    playerAugment4 = db.Column(db.String(256))
    playerScore0 = db.Column(db.String(256))
    playerScore1 = db.Column(db.String(256))
    playerScore10 = db.Column(db.String(256))
    playerScore11 = db.Column(db.String(256))
    playerScore2 = db.Column(db.String(256))
    playerScore3 = db.Column(db.String(256))
    playerScore4 = db.Column(db.String(256))
    playerScore5 = db.Column(db.String(256))
    playerScore6 = db.Column(db.String(256))
    playerScore7 = db.Column(db.String(256))
    playerScore8 = db.Column(db.String(256))
    playerScore9 = db.Column(db.String(256))
    playerSubteamId = db.Column(db.String(256))
    profileIcon = db.Column(db.String(256))
    pushPings = db.Column(db.String(256))
    puuid = db.Column(db.String(256))
    quadraKills = db.Column(db.String(256))
    riotIdGameName = db.Column(db.String(256))
    riotIdTagline = db.Column(db.String(256))
    role = db.Column(db.String(256))
    sightWardsBoughtInGame = db.Column(db.String(256))
    spell1Casts = db.Column(db.String(256))
    spell2Casts = db.Column(db.String(256))
    spell3Casts = db.Column(db.String(256))
    spell4Casts = db.Column(db.String(256))
    subteamPlacement = db.Column(db.String(256))
    summoner1Casts = db.Column(db.String(256))
    summoner1Id = db.Column(db.String(256))
    summoner2Casts = db.Column(db.String(256))
    summoner2Id = db.Column(db.String(256))
    summonerId = db.Column(db.String(256))
    summonerLevel = db.Column(db.String(256))
    summonerName = db.Column(db.String(256))
    teamEarlySurrendered = db.Column(db.String(256))
    teamId = db.Column(db.String(256))
    teamPosition = db.Column(db.String(256))
    timeCCingOthers = db.Column(db.String(256))
    timePlayed = db.Column(db.String(256))
    totalAllyJungleMinionsKilled = db.Column(db.String(256))
    totalDamageDealt = db.Column(db.String(256))
    totalDamageDealtToChampions = db.Column(db.String(256))
    totalDamageShieldedOnTeammates = db.Column(db.String(256))
    totalDamageTaken = db.Column(db.String(256))
    totalEnemyJungleMinionsKilled = db.Column(db.String(256))
    totalHeal = db.Column(db.String(256))
    totalHealsOnTeammates = db.Column(db.String(256))
    totalMinionsKilled = db.Column(db.String(256))
    totalTimeCCDealt = db.Column(db.String(256))
    totalTimeSpentDead = db.Column(db.String(256))
    totalUnitsHealed = db.Column(db.String(256))
    tripleKills = db.Column(db.String(256))
    trueDamageDealt = db.Column(db.String(256))
    trueDamageDealtToChampions = db.Column(db.String(256))
    trueDamageTaken = db.Column(db.String(256))
    turretKills = db.Column(db.String(256))
    turretTakedowns = db.Column(db.String(256))
    turretsLost = db.Column(db.String(256))
    unrealKills = db.Column(db.String(256))
    visionClearedPings = db.Column(db.String(256))
    visionScore = db.Column(db.String(256))
    visionWardsBoughtInGame = db.Column(db.String(256))
    wardsKilled = db.Column(db.String(256))
    wardsPlaced = db.Column(db.String(256))
    win = db.Column(db.String(256))
