import json

# JSON data
data = {
      "ASSISTS": "12",
      "BARON_KILLS": "0",
      "BARRACKS_KILLED": "0",
      "BARRACKS_TAKEDOWNS": "2",
      "BOUNTY_LEVEL": "1",
      "CHAMPION_MISSION_STAT_0": "0",
      "CHAMPION_MISSION_STAT_1": "0",
      "CHAMPION_MISSION_STAT_2": "0",
      "CHAMPION_MISSION_STAT_3": "0",
      "CHAMPIONS_KILLED": "6",
      "CHAMPION_TRANSFORM": "0",
      "CONSUMABLES_PURCHASED": "0",
      "DOUBLE_KILLS": "0",
      "DRAGON_KILLS": "0",
      "EXP": "22407",
      "FRIENDLY_DAMPEN_LOST": "0",
      "FRIENDLY_HQ_LOST": "0",
      "FRIENDLY_TURRET_LOST": "0",
      "GAME_ENDED_IN_EARLY_SURRENDER": "0",
      "GAME_ENDED_IN_SURRENDER": "0",
      "GOLD_EARNED": "13598",
      "GOLD_SPENT": "10300",
      "HQ_KILLED": "0",
      "HQ_TAKEDOWNS": "0",
      "ID": "2157933141938048",
      "INDIVIDUAL_POSITION": "Invalid",
      "ITEM0": "6653",
      "ITEM1": "3020",
      "ITEM2": "4637",
      "ITEM3": "3165",
      "ITEM4": "0",
      "ITEM5": "0",
      "ITEM6": "2052",
      "ITEMS_PURCHASED": "6",
      "KEYSTONE_ID": "8128",
      "KILLING_SPREES": "1",
      "LARGEST_CRITICAL_STRIKE": "0",
      "LARGEST_KILLING_SPREE": "2",
      "LARGEST_MULTI_KILL": "1",
      "LEVEL": "18",
      "LONGEST_TIME_SPENT_LIVING": "321",
      "MAGIC_DAMAGE_DEALT_PLAYER": "42094",
      "MAGIC_DAMAGE_DEALT_TO_CHAMPIONS": "26789",
      "MAGIC_DAMAGE_TAKEN": "7490",
      "MINIONS_KILLED": "42",
      "MUTED_ALL": "0",
      "NAME": "Thotiana2210",
      "NEUTRAL_MINIONS_KILLED": "0",
      "NEUTRAL_MINIONS_KILLED_ENEMY_JUNGLE": "0",
      "NEUTRAL_MINIONS_KILLED_YOUR_JUNGLE": "0",
      "NODE_CAPTURE": "0",
      "NODE_CAPTURE_ASSIST": "0",
      "NODE_NEUTRALIZE": "0",
      "NODE_NEUTRALIZE_ASSIST": "0",
      "NUM_DEATHS": "5",
      "OBJECTIVES_STOLEN": "0",
      "OBJECTIVES_STOLEN_ASSISTS": "0",
      "PENTA_KILLS": "0",
      "PERK0": "8128",
      "PERK0_VAR1": "1101",
      "PERK0_VAR2": "19",
      "PERK0_VAR3": "0",
      "PERK1": "8126",
      "PERK1_VAR1": "1132",
      "PERK1_VAR2": "0",
      "PERK1_VAR3": "0",
      "PERK2": "8138",
      "PERK2_VAR1": "30",
      "PERK2_VAR2": "0",
      "PERK2_VAR3": "0",
      "PERK3": "8106",
      "PERK3_VAR1": "5",
      "PERK3_VAR2": "0",
      "PERK3_VAR3": "0",
      "PERK4": "8009",
      "PERK4_VAR1": "2383",
      "PERK4_VAR2": "0",
      "PERK4_VAR3": "0",
      "PERK5": "8014",
      "PERK5_VAR1": "870",
      "PERK5_VAR2": "0",
      "PERK5_VAR3": "0",
      "PERK_PRIMARY_STYLE": "8100",
      "PERK_SUB_STYLE": "8000",
      "PHYSICAL_DAMAGE_DEALT_PLAYER": "5198",
      "PHYSICAL_DAMAGE_DEALT_TO_CHAMPIONS": "430",
      "PHYSICAL_DAMAGE_TAKEN": "6487",
      "PING": "29",
      "PLAYER_POSITION": "2",
      "PLAYER_ROLE": "1",
      "PLAYER_SCORE_0": "0",
      "PLAYER_SCORE_1": "0",
      "PLAYER_SCORE_10": "0",
      "PLAYER_SCORE_11": "0",
      "PLAYER_SCORE_2": "0",
      "PLAYER_SCORE_3": "0",
      "PLAYER_SCORE_4": "0",
      "PLAYER_SCORE_5": "0",
      "PLAYER_SCORE_6": "0",
      "PLAYER_SCORE_7": "0",
      "PLAYER_SCORE_8": "0",
      "PLAYER_SCORE_9": "0",
      "PLAYERS_I_MUTED": "0",
      "PLAYERS_THAT_MUTED_ME": "0",
      "QUADRA_KILLS": "0",
      "SIGHT_WARDS_BOUGHT_IN_GAME": "0",
      "SKIN": "Teemo",
      "SPELL1_CAST": "29",
      "SPELL2_CAST": "17",
      "SPELL3_CAST": "0",
      "SPELL4_CAST": "49",
      "STAT_PERK_0": "5008",
      "STAT_PERK_1": "5008",
      "STAT_PERK_2": "5002",
      "SUMMON_SPELL1_CAST": "3",
      "SUMMON_SPELL2_CAST": "4",
      "TEAM": "100",
      "TEAM_EARLY_SURRENDERED": "0",
      "TEAM_OBJECTIVE": "0",
      "TEAM_POSITION": 0,
      "TIME_CCING_OTHERS": "54",
      "TIME_OF_FROM_LAST_DISCONNECT": "0",
      "TIME_PLAYED": "1319",
      "TIME_SPENT_DISCONNECTED": "0",
      "TOTAL_DAMAGE_DEALT": "49734",
      "TOTAL_DAMAGE_DEALT_TO_BUILDINGS": "1513",
      "TOTAL_DAMAGE_DEALT_TO_CHAMPIONS": "29660",
      "TOTAL_DAMAGE_DEALT_TO_OBJECTIVES": "1513",
      "TOTAL_DAMAGE_DEALT_TO_TURRETS": "1513",
      "TOTAL_DAMAGE_SELF_MITIGATED": "5843",
      "TOTAL_DAMAGE_SHIELDED_ON_TEAMMATES": "0",
      "TOTAL_DAMAGE_TAKEN": "14327",
      "TOTAL_HEAL": "2633",
      "TOTAL_HEAL_ON_TEAMMATES": "0",
      "TOTAL_TIME_CROWD_CONTROL_DEALT": "311",
      "TOTAL_TIME_SPENT_DEAD": "102",
      "TOTAL_UNITS_HEALED": "1",
      "TRIPLE_KILLS": "0",
      "TRUE_DAMAGE_DEALT_PLAYER": "2440",
      "TRUE_DAMAGE_DEALT_TO_CHAMPIONS": "2440",
      "TRUE_DAMAGE_TAKEN": "349",
      "TURRETS_KILLED": "1",
      "TURRET_TAKEDOWNS": "3",
      "UNREAL_KILLS": "0",
      "VICTORY_POINT_TOTAL": "0",
      "VISION_SCORE": "0",
      "VISION_WARDS_BOUGHT_IN_GAME": "0",
      "WARD_KILLED": "0",
      "WARD_PLACED": "0",
      "WARD_PLACED_DETECTOR": "0",
      "WAS_AFK": "0",
      "WAS_AFK_AFTER_FAILED_SURRENDER": "0",
      "WAS_EARLY_SURRENDER_ACCOMPLICE": "0",
      "WAS_LEAVER": "0",
      "WAS_SURRENDER_DUE_TO_AFK": "0",
      "WIN": "Win"
    }

# Template
template = []
for idx, x in enumerate(data):
    template.append('{*},')
    print(len(template))
# Replace "*" with keys from the JSON data
replaced_template = []
for idx, x in enumerate(data):
    replaced_template.append(template[idx])

for idx, key in enumerate(data):
    replaced_template[idx] = replaced_template[idx].replace('*', key)

# Print the replaced template
#print(replaced_template)
f = open("demofile2.txt", "w")
for idx, x in enumerate(data):
    print(idx)
    f.write(replaced_template[idx])
f.close()